// AUTO-GENERATED by scripts/generate_nyc_map/generate_map.py — do not edit by hand.
// The map image is geo-referenced so pixel <-> lat/lng conversion is available.

export const MAP_META = {
  "width": 4096,
  "height": 3464,
  "bbox": {
    "west": -74.025,
    "south": 40.642,
    "east": -73.791,
    "north": 40.792
  }
}

export function pixelToLatLng(x, y) {
  const { west, south, east, north } = MAP_META.bbox
  const lng = west + (x / MAP_META.width) * (east - west)
  const lat = north - (y / MAP_META.height) * (north - south)
  return { lat, lng }
}

export function latLngToPixel(lat, lng) {
  const { west, south, east, north } = MAP_META.bbox
  const x = ((lng - west) / (east - west)) * MAP_META.width
  const y = ((north - lat) / (north - south)) * MAP_META.height
  return { x, y }
}
